product_by_id:
    path: /product/{id}
    controller: App\Controller\ProductsController::getProductById
    methods: [GET]
    requiments:
        id: '[0-9]+'

product_create:
    path: /product
    controller: App\Controller\ProductsController::createProduct
    methods: [POST]

product_delete:
    path: /product
    controller: App\Controller\ProductsController::deleteProduct
    methods: [DELETE]

products_list:
    path: /product/all
    controller: App\Controller\ProductsController::listAllProducts
    methods: [GET]

categories_list:
    path: /category
    controller: App\Controller\CategoriesController::listAllCategories
    methods: [GET]